# -*- coding: utf-8 -*-
"""my_code.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c_PidR0K3kHpyimeOJ8DsyqHayo3qCoo
"""

type("I just created my_code file")

fruits = ['mango', 'pineapple', 'banana', 'cherry', 'avocado']
fruits[0]

def cube(number):
  return number**3
marks = [1,2,3,4,5]
list(map(cube, marks))